import type { Project, Unit, Zone, Developer, DeveloperProgress, User } from './types';

// Mock Users
export const users: User[] = [
  {
    id: '1',
    email: 'admin@alamalrealestate.com',
    name: 'Ahmed Hassan',
    phone: '+20 100 123 4567',
    role: 'admin',
    createdAt: '2024-01-01',
  },
  {
    id: '2',
    email: 'agent@alamalrealestate.com',
    name: 'Sara Mohamed',
    phone: '+20 101 234 5678',
    role: 'agent',
    createdAt: '2024-02-15',
  },
];

// Mock Zones
export const zones: Zone[] = [
  {
    id: 'zone-1',
    name: 'New Cairo',
    nameAr: 'القاهرة الجديدة',
    description: 'A modern urban development featuring world-class infrastructure, premium residential compounds, and extensive green spaces. Home to some of Egypt\'s most prestigious addresses.',
    descriptionAr: 'تطوير حضري عصري يتميز ببنية تحتية عالمية المستوى ومجمعات سكنية متميزة ومساحات خضراء واسعة.',
    image: '/images/zones/new-cairo.jpg',
    location: 'East Cairo, Egypt',
    projectCount: 8,
    unitCount: 1250,
    createdAt: '2024-01-01',
  },
  {
    id: 'zone-2',
    name: '6th of October City',
    nameAr: 'مدينة السادس من أكتوبر',
    description: 'A thriving satellite city west of Cairo, known for its educational institutions, industrial zones, and expanding residential areas with modern amenities.',
    descriptionAr: 'مدينة ساتلايت مزدهرة غرب القاهرة، تشتهر بمؤسساتها التعليمية ومناطقها الصناعية.',
    image: '/images/zones/october.jpg',
    location: 'West Cairo, Egypt',
    projectCount: 6,
    unitCount: 980,
    createdAt: '2024-01-01',
  },
  {
    id: 'zone-3',
    name: 'North Coast',
    nameAr: 'الساحل الشمالي',
    description: 'Egypt\'s premier Mediterranean destination featuring pristine beaches, luxury resorts, and exclusive residential communities along the stunning coastline.',
    descriptionAr: 'وجهة مصر الأولى على البحر المتوسط تضم شواطئ بكر ومنتجعات فاخرة.',
    image: '/images/zones/north-coast.jpg',
    location: 'Mediterranean Coast, Egypt',
    projectCount: 5,
    unitCount: 720,
    createdAt: '2024-01-01',
  },
  {
    id: 'zone-4',
    name: 'New Administrative Capital',
    nameAr: 'العاصمة الإدارية الجديدة',
    description: 'Egypt\'s ambitious new capital city featuring state-of-the-art infrastructure, government buildings, and premium residential and commercial developments.',
    descriptionAr: 'عاصمة مصر الجديدة الطموحة تضم بنية تحتية متطورة ومباني حكومية.',
    image: '/images/zones/capital.jpg',
    location: 'East of Cairo, Egypt',
    projectCount: 12,
    unitCount: 2100,
    createdAt: '2024-01-01',
  },
];

// Mock Developers
export const developers: Developer[] = [
  {
    id: 'dev-1',
    name: 'Al Amal Development',
    nameAr: 'الأمل للتطوير العقاري',
    description: 'Leading real estate developer with over 25 years of experience in creating exceptional living spaces. Known for innovative designs and timely delivery.',
    descriptionAr: 'شركة رائدة في التطوير العقاري بخبرة تتجاوز 25 عاماً في إنشاء مساحات معيشية استثنائية.',
    logo: '/images/developers/alamal-logo.jpg',
    website: 'https://alamaldevelopment.com',
    projectsCount: 15,
    establishedYear: 1998,
    headquarters: 'Cairo, Egypt',
    createdAt: '2024-01-01',
  },
  {
    id: 'dev-2',
    name: 'Palm Hills Developments',
    nameAr: 'بالم هيلز للتعمير',
    description: 'One of Egypt\'s most prominent real estate developers, known for creating integrated communities that redefine modern living.',
    descriptionAr: 'واحدة من أبرز شركات التطوير العقاري في مصر، معروفة بإنشاء مجتمعات متكاملة.',
    logo: '/images/developers/palmhills-logo.jpg',
    website: 'https://palmhillsdevelopments.com',
    projectsCount: 28,
    establishedYear: 2005,
    headquarters: 'Cairo, Egypt',
    createdAt: '2024-01-01',
  },
  {
    id: 'dev-3',
    name: 'SODIC',
    nameAr: 'سوديك',
    description: 'Award-winning developer focused on sustainable communities with world-class amenities and thoughtful urban planning.',
    descriptionAr: 'مطور حائز على جوائز يركز على المجتمعات المستدامة مع وسائل راحة عالمية المستوى.',
    logo: '/images/developers/sodic-logo.jpg',
    website: 'https://sodic.com',
    projectsCount: 22,
    establishedYear: 1996,
    headquarters: 'Cairo, Egypt',
    createdAt: '2024-01-01',
  },
];

// Mock Projects
export const projects: Project[] = [
  {
    id: 'proj-1',
    name: 'Al Amal Gardens',
    nameAr: 'حدائق الأمل',
    description: 'A luxurious residential compound featuring spacious villas and apartments surrounded by lush green landscapes. Experience the perfect blend of modern architecture and natural beauty with premium amenities including a clubhouse, swimming pools, and sports facilities.',
    descriptionAr: 'مجمع سكني فاخر يضم فيلات وشقق واسعة محاطة بمناظر طبيعية خضراء خلابة.',
    location: 'New Cairo, Egypt',
    locationAr: 'القاهرة الجديدة، مصر',
    latitude: 30.0291,
    longitude: 31.4645,
    images: ['/images/projects/alamal-gardens-1.jpg', '/images/projects/alamal-gardens-2.jpg'],
    priceFrom: 3500000,
    priceTo: 15000000,
    currency: 'EGP',
    totalUnits: 250,
    availableUnits: 85,
    amenities: ['Swimming Pool', 'Gym', 'Clubhouse', 'Kids Area', '24/7 Security', 'Green Spaces'],
    developerId: 'dev-1',
    zoneId: 'zone-1',
    status: 'under-construction',
    completionDate: '2026-06-01',
    createdAt: '2024-01-01',
  },
  {
    id: 'proj-2',
    name: 'Sunset Villas',
    nameAr: 'فلل الغروب',
    description: 'Exclusive collection of Mediterranean-style villas offering panoramic views and private gardens. Each villa features premium finishes, smart home technology, and generous outdoor spaces for ultimate comfort and privacy.',
    descriptionAr: 'مجموعة حصرية من الفيلات على الطراز المتوسطي توفر إطلالات بانورامية وحدائق خاصة.',
    location: 'North Coast, Egypt',
    locationAr: 'الساحل الشمالي، مصر',
    latitude: 31.0461,
    longitude: 29.7565,
    images: ['/images/projects/sunset-villas-1.jpg', '/images/projects/sunset-villas-2.jpg'],
    priceFrom: 8000000,
    priceTo: 25000000,
    currency: 'EGP',
    totalUnits: 120,
    availableUnits: 42,
    amenities: ['Private Beach', 'Marina', 'Golf Course', 'Spa', 'Fine Dining', 'Concierge'],
    developerId: 'dev-2',
    zoneId: 'zone-3',
    status: 'ready',
    completionDate: '2024-12-01',
    createdAt: '2024-01-01',
  },
  {
    id: 'proj-3',
    name: 'Capital Heights',
    nameAr: 'كابيتال هايتس',
    description: 'A landmark mixed-use development in the heart of the New Administrative Capital. Featuring luxury apartments, penthouses, and commercial spaces with stunning city views and direct access to major transportation hubs.',
    descriptionAr: 'مشروع متعدد الاستخدامات في قلب العاصمة الإدارية الجديدة.',
    location: 'New Administrative Capital, Egypt',
    locationAr: 'العاصمة الإدارية الجديدة، مصر',
    latitude: 30.0130,
    longitude: 31.7277,
    images: ['/images/projects/capital-heights-1.jpg', '/images/projects/capital-heights-2.jpg'],
    priceFrom: 2000000,
    priceTo: 12000000,
    currency: 'EGP',
    totalUnits: 500,
    availableUnits: 320,
    amenities: ['Rooftop Pool', 'Business Center', 'Underground Parking', 'Retail Mall', 'Kids Club'],
    developerId: 'dev-3',
    zoneId: 'zone-4',
    status: 'under-construction',
    completionDate: '2027-03-01',
    createdAt: '2024-01-01',
  },
  {
    id: 'proj-4',
    name: 'October Oasis',
    nameAr: 'واحة أكتوبر',
    description: 'A family-oriented community featuring diverse housing options from cozy apartments to spacious villas. Enjoy resort-style living with extensive recreational facilities and top-tier educational institutions nearby.',
    descriptionAr: 'مجتمع موجه للعائلات يضم خيارات سكنية متنوعة من الشقق إلى الفيلات الواسعة.',
    location: '6th of October City, Egypt',
    locationAr: 'مدينة السادس من أكتوبر، مصر',
    latitude: 29.9729,
    longitude: 30.9444,
    images: ['/images/projects/october-oasis-1.jpg', '/images/projects/october-oasis-2.jpg'],
    priceFrom: 1500000,
    priceTo: 8000000,
    currency: 'EGP',
    totalUnits: 400,
    availableUnits: 180,
    amenities: ['Water Park', 'Sports Complex', 'Shopping Center', 'Medical Center', 'Schools'],
    developerId: 'dev-1',
    zoneId: 'zone-2',
    status: 'under-construction',
    completionDate: '2025-12-01',
    createdAt: '2024-01-01',
  },
];

// Mock Units
export const units: Unit[] = [
  {
    id: 'unit-1',
    name: 'Garden Villa A1',
    nameAr: 'فيلا حديقة A1',
    type: 'villa',
    projectId: 'proj-1',
    description: 'Stunning standalone villa with private garden and pool. Features 4 bedrooms, modern kitchen, and spacious living areas. Premium finishes throughout with marble flooring and designer fixtures.',
    descriptionAr: 'فيلا مستقلة مذهلة مع حديقة خاصة وحمام سباحة.',
    images: ['/images/units/villa-a1-1.jpg', '/images/units/villa-a1-2.jpg', '/images/units/villa-a1-3.jpg'],
    price: 12500000,
    currency: 'EGP',
    area: 350,
    areaUnit: 'sqm',
    bedrooms: 4,
    bathrooms: 5,
    floors: 2,
    parkingSpaces: 2,
    features: ['Private Pool', 'Garden', 'Smart Home', 'Maid Room', 'Storage'],
    status: 'available',
    floorPlan: '/images/floorplans/villa-a1.jpg',
    createdAt: '2024-01-01',
  },
  {
    id: 'unit-2',
    name: 'Sky Apartment B12',
    nameAr: 'شقة سكاي B12',
    type: 'apartment',
    projectId: 'proj-3',
    description: 'Modern 3-bedroom apartment with stunning city views. Open-plan living and dining area, fully equipped kitchen, and private balcony. Building amenities include gym, pool, and 24/7 concierge.',
    descriptionAr: 'شقة حديثة من 3 غرف نوم مع إطلالات مذهلة على المدينة.',
    images: ['/images/units/apt-b12-1.jpg', '/images/units/apt-b12-2.jpg'],
    price: 4500000,
    currency: 'EGP',
    area: 180,
    areaUnit: 'sqm',
    bedrooms: 3,
    bathrooms: 3,
    floors: 1,
    parkingSpaces: 1,
    features: ['City View', 'Balcony', 'Central AC', 'Built-in Wardrobes'],
    status: 'available',
    floorPlan: '/images/floorplans/apt-b12.jpg',
    createdAt: '2024-01-01',
  },
  {
    id: 'unit-3',
    name: 'Beachfront Villa C5',
    nameAr: 'فيلا الشاطئ C5',
    type: 'villa',
    projectId: 'proj-2',
    description: 'Exclusive beachfront villa with direct sea access. Features 5 bedrooms, infinity pool, and stunning Mediterranean views. Perfect for those seeking luxury coastal living.',
    descriptionAr: 'فيلا حصرية على الشاطئ مع وصول مباشر للبحر.',
    images: ['/images/units/beach-villa-1.jpg', '/images/units/beach-villa-2.jpg'],
    price: 22000000,
    currency: 'EGP',
    area: 450,
    areaUnit: 'sqm',
    bedrooms: 5,
    bathrooms: 6,
    floors: 2,
    parkingSpaces: 3,
    features: ['Beach Access', 'Infinity Pool', 'Sea View', 'Private Dock', 'Outdoor Kitchen'],
    status: 'available',
    createdAt: '2024-01-01',
  },
  {
    id: 'unit-4',
    name: 'Townhouse D8',
    nameAr: 'تاون هاوس D8',
    type: 'townhouse',
    projectId: 'proj-4',
    description: 'Elegant townhouse in a prime location with private garden and rooftop terrace. Perfect for families with 4 bedrooms, modern amenities, and close proximity to schools and shopping.',
    descriptionAr: 'تاون هاوس أنيق في موقع متميز مع حديقة خاصة وتراس على السطح.',
    images: ['/images/units/townhouse-d8-1.jpg', '/images/units/townhouse-d8-2.jpg'],
    price: 5800000,
    currency: 'EGP',
    area: 280,
    areaUnit: 'sqm',
    bedrooms: 4,
    bathrooms: 4,
    floors: 3,
    parkingSpaces: 2,
    features: ['Garden', 'Rooftop Terrace', 'Near Schools', 'Central Location'],
    status: 'reserved',
    createdAt: '2024-01-01',
  },
  {
    id: 'unit-5',
    name: 'Penthouse E1',
    nameAr: 'بنتهاوس E1',
    type: 'penthouse',
    projectId: 'proj-3',
    description: 'Luxurious penthouse with panoramic 360-degree views. Features private elevator access, rooftop pool, and ultra-modern finishes. The epitome of urban luxury living.',
    descriptionAr: 'بنتهاوس فاخر مع إطلالات بانورامية 360 درجة.',
    images: ['/images/units/penthouse-e1-1.jpg', '/images/units/penthouse-e1-2.jpg'],
    price: 11500000,
    currency: 'EGP',
    area: 320,
    areaUnit: 'sqm',
    bedrooms: 4,
    bathrooms: 5,
    floors: 2,
    parkingSpaces: 2,
    features: ['Private Elevator', 'Rooftop Pool', '360° View', 'Home Theater', 'Wine Cellar'],
    status: 'available',
    createdAt: '2024-01-01',
  },
  {
    id: 'unit-6',
    name: 'Studio F3',
    nameAr: 'استوديو F3',
    type: 'studio',
    projectId: 'proj-3',
    description: 'Modern studio apartment perfect for young professionals. Efficiently designed with premium finishes, built-in storage, and access to all building amenities.',
    descriptionAr: 'شقة استوديو حديثة مثالية للمهنيين الشباب.',
    images: ['/images/units/studio-f3-1.jpg'],
    price: 1800000,
    currency: 'EGP',
    area: 65,
    areaUnit: 'sqm',
    bedrooms: 0,
    bathrooms: 1,
    floors: 1,
    parkingSpaces: 1,
    features: ['Built-in Kitchen', 'City View', 'Gym Access', 'Concierge'],
    status: 'available',
    createdAt: '2024-01-01',
  },
  {
    id: 'unit-7',
    name: 'Duplex G2',
    nameAr: 'دوبلكس G2',
    type: 'duplex',
    projectId: 'proj-1',
    description: 'Spacious duplex with modern design and garden view. Features open-plan living, 3 bedrooms on the upper floor, and a private terrace for outdoor entertaining.',
    descriptionAr: 'دوبلكس واسع بتصميم حديث وإطلالة على الحديقة.',
    images: ['/images/units/duplex-g2-1.jpg', '/images/units/duplex-g2-2.jpg'],
    price: 7200000,
    currency: 'EGP',
    area: 240,
    areaUnit: 'sqm',
    bedrooms: 3,
    bathrooms: 3,
    floors: 2,
    parkingSpaces: 2,
    features: ['Garden View', 'Private Terrace', 'Modern Kitchen', 'Built-in Wardrobes'],
    status: 'available',
    createdAt: '2024-01-01',
  },
  {
    id: 'unit-8',
    name: 'Family Apartment H5',
    nameAr: 'شقة عائلية H5',
    type: 'apartment',
    projectId: 'proj-4',
    description: 'Perfect family apartment with 3 bedrooms and generous living spaces. Located near the community center with easy access to schools, parks, and shopping.',
    descriptionAr: 'شقة عائلية مثالية من 3 غرف نوم ومساحات معيشة واسعة.',
    images: ['/images/units/family-apt-1.jpg', '/images/units/family-apt-2.jpg'],
    price: 3200000,
    currency: 'EGP',
    area: 165,
    areaUnit: 'sqm',
    bedrooms: 3,
    bathrooms: 2,
    floors: 1,
    parkingSpaces: 1,
    features: ['Near Schools', 'Garden View', 'Storage Room', 'Playground Access'],
    status: 'sold',
    createdAt: '2024-01-01',
  },
];

// Mock Developer Progress
export const developerProgress: DeveloperProgress[] = [
  {
    id: 'prog-1',
    projectId: 'proj-1',
    title: 'Foundation & Structure Complete',
    description: 'All foundation work and main structural elements for Phase 1 villas have been completed. Steel framework is in place and concrete pouring is finished.',
    progress: 45,
    images: ['/images/progress/prog-1-1.jpg', '/images/progress/prog-1-2.jpg'],
    milestone: 'Phase 1 Structure',
    expectedCompletion: '2025-03-01',
    updatedAt: '2024-11-15',
  },
  {
    id: 'prog-2',
    projectId: 'proj-3',
    title: 'Tower A Exterior Complete',
    description: 'Exterior cladding and windows installation for Tower A completed. Interior work has commenced on floors 1-15.',
    progress: 60,
    images: ['/images/progress/prog-2-1.jpg'],
    milestone: 'Tower A Finishing',
    expectedCompletion: '2026-06-01',
    updatedAt: '2024-12-01',
  },
  {
    id: 'prog-3',
    projectId: 'proj-4',
    title: 'Landscaping Begins',
    description: 'Main infrastructure complete. Landscaping work has started including parks, walking paths, and community gardens.',
    progress: 70,
    images: ['/images/progress/prog-3-1.jpg'],
    milestone: 'Community Spaces',
    expectedCompletion: '2025-06-01',
    updatedAt: '2024-12-10',
  },
  {
    id: 'prog-4',
    projectId: 'proj-2',
    title: 'Final Handover Phase',
    description: 'Villas 1-80 have been handed over. Remaining units are in final inspection and snagging phase.',
    progress: 95,
    images: ['/images/progress/prog-4-1.jpg'],
    milestone: 'Handover',
    expectedCompletion: '2025-01-15',
    updatedAt: '2024-12-20',
  },
];

// Helper functions
export function formatPrice(price: number, currency: string = 'EGP'): string {
  return new Intl.NumberFormat('en-EG', {
    style: 'currency',
    currency: currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}

export function formatArea(area: number, unit: 'sqm' | 'sqft' = 'sqm'): string {
  return `${area.toLocaleString()} ${unit === 'sqm' ? 'm²' : 'ft²'}`;
}

export function getProjectById(id: string): Project | undefined {
  return projects.find(p => p.id === id);
}

export function getUnitById(id: string): Unit | undefined {
  return units.find(u => u.id === id);
}

export function getZoneById(id: string): Zone | undefined {
  return zones.find(z => z.id === id);
}

export function getDeveloperById(id: string): Developer | undefined {
  return developers.find(d => d.id === id);
}

export function getUnitsByProject(projectId: string): Unit[] {
  return units.filter(u => u.projectId === projectId);
}

export function getProjectsByZone(zoneId: string): Project[] {
  return projects.filter(p => p.zoneId === zoneId);
}

export function getProjectsByDeveloper(developerId: string): Project[] {
  return projects.filter(p => p.developerId === developerId);
}

export function getProgressByProject(projectId: string): DeveloperProgress[] {
  return developerProgress.filter(p => p.projectId === projectId);
}
